### ISSUE TITLE
Adding images from a folder and its subfolders

### ISSUE THREAD

**Issue by vivadavid** [Panda-Sharp/Yugen.Mosaic#16]
Hi!

After reading an article on Windows Central about UWP apps, I learnt about Yugen Mosaic and I installed it on my laptop. It's great!

Sometimes you want to create a mosaic from all the images located in a folder or even in a folder and its subfolders. I was wondering if you'd consider adding this feature.

Thank you and keep up the good work!

**Comment by emiliano84** [comment]
Hi @vivadavid 

Thanks a lot for your lovely feedback, I'll be glad to add this useful feature in a next release :)

Cheers !

**Comment by vivadavid** [comment]
Thank you, @emiliano84 !

**Comment by emiliano84** [comment]
Hi @vivadavid , I'll release a new update including also the feature you requested next week :)

**Comment by vivadavid** [comment]
> Hi @vivadavid , I'll release a new update including also the feature you requested next week :)

That's great! Thank you!

**Comment by emiliano84** [comment]
Available in v1.2.3.0

**Comment by vivadavid** [comment]
Hi, @emiliano84 

I wanted to inform you that I've tried the new feature.

After selecting a particular folder, the thumbnails of the images are displayed on the left panel but, at some point, the app just crashes. Let me know if there's a way to provide you with a log or relevant information. My laptop runs Windows 10 x64 (18363.900).

**Comment by emiliano84** [comment]
Hi @vivadavid  thanks for your feedback, I was able to reproduce the crash, I'll try to fix it ASAP

**Comment by vivadavid** [comment]
Thank you, @emiliano84 !

**Comment by emiliano84** [comment]
Hi @vivadavid sorry for the delay, but the fix should be finally available in the store v1.2.4.0

Let me know if you face any other issue, thanks

**Comment by vivadavid** [comment]
Hi, @emiliano84 ,

Thank you for your message and for the new version, that I tested last evening:

1. If you select a folder that directly contains pictures, it seems to work.

2. However, if you select a folder that contains a structure of subfolders that ultimately contain images, it doesn't seem to work, unless I didn't wait enough.

3. At some point, my laptop just froze and I had to turn it off. I wonder if this happened because I tried several times to load the images of a structure of subfolders and there were too many processes going on.

4. Also, have you considered omitting the creation of thumbnails for the tiles list and replacing these thumbnails for just a progress bar and the number of images that will be used for the creation of the mosaic? This thumbnail creation might be too much for older computers.

I'll be glad to give you more feedback if you need it. Thanks again!

**Comment by emiliano84** [comment]
Hi @vivadavid ,

thanks again for your detailed feedback, I'll try to investigate, probably I'm going to create a VM with low specs to understand better, it's the first time I work with image processing, I'm still learning :) I'll keep you posted

**Comment by vivadavid** [comment]
I appreciate it, @emiliano84.

**Comment by emiliano84** [comment]
Hi @vivadavid I just released an update, I addressed some issues and improvements but still there is room them, I have just been super busy with other works, give it a spin and let me know how it goes.

cheers

**Comment by vivadavid** [comment]
Hi, @emiliano84 ,

Thank you for the update! I've done two tests and, unfortunately, it didn't work for me. At least, my PC didn't freeze this time.

1. In my first test, it looks like all the tiles were loaded, but when I clicked on Generate, the app crashed some time later.

2. In my second test, the app crashed before all the tiles were loaded.

Let me know if I can provide you more information and thank you again for your time.

**Comment by emiliano84** [comment]
Hi @vivadavid 

I didn't forget, I have been busy and now I'll go a bit on holiday, after the second half of September I'll restart to work on this, I'll have also a new feature in mind to implement :)

**Comment by vivadavid** [comment]
Thank you for your message, @emiliano84 . Have fun in your holidays and I'll be happy to try that new feature in the Autumn.

**Comment by Panda-Sharp** [comment]
Hi @vivadavid sorry for the long delay, but I just released and update that should improve the performance and resources usage, plus adding an ASCII art feature :) feel free to share your feedbacks, thanks!

**Comment by vivadavid** [comment]
Hi, @Panda-Sharp,

Actually, the other day I was wondering what happened with Yugen Mosaic: I'm glad it's back. I tested the new version a while ago, but it got stuck. Bear in mind that my new laptop is being repaired and I'm currently using an old machine with only 4 GB of RAM. I've tried again now and it worked! The first time I was probably doing too many tasks at the same time and my PC couldn't cope and overheated. I've also tried the new ASCII mode and I love it!

I'd like to make two more comments:

1. I got a notification about the new comment on this thread, but not about the new version, and in fact, there's nothing about it in the Releases section.

2. Would you consider increasing the size of the icon? It looks smaller than most of the icons of my other apps.
![Yugen Mosaic](https://user-images.githubusercontent.com/9334287/124515565-146c8080-dde0-11eb-8a12-9f40cea16060.png)


When I get my new laptop back, I will have another look at the new version of Mosaic.  Thanks for your work!

**Comment by Panda-Sharp** [comment]
Hi @vivadavid 

I'm glad that the app works better for you and that you love the ASCII mode :)

Regarding your feedbacks:
1- It's right, I didn't create a release on GH, it's manual I will do it and also I will try to make it automatic from the CI/CD pipeline next time 
2- That's a good feedback, I will for sure

Thanks!

**Comment by Panda-Sharp** [comment]
Hi @vivadavid sorry for the delay, but has been a crazy time, I released a new update with a bigger icon, can you kindly check it out? I was busy releasing yugen dj for the launch 2021. I will try to work on GH releases next week, thanks 🙂

**Comment by vivadavid** [comment]
Hi, @Panda-Sharp: the icon looks the proper size now. Thanks!

**Comment by Panda-Sharp** [comment]
Hi @vivadavid me again, I also tweaked the pipeline to automatically create a new release on GH when a new update has been released to the store, I'm going to close this issue now, thank you so much for your feedbacks :)

P.S.
If you already didn't take a look at all the apps launched by the community few days ago https://uwpcommunity.com/launch/2021/

**Comment by vivadavid** [comment]
Hi, @Panda-Sharp ! Thank you for the link! I already knew some of the apps, but I have discovered others. Take care and keep up the good work!
